version: "3"

services:
  cyphernode_welcome:
    image: nkitzke/phiboxapp:0.0.1
    volumes:
      - "$GATEKEEPER_DATAPATH/certs/cert.pem:/data/cert.pem"
      - "$GATEKEEPER_DATAPATH/keys.properties:/data/keys.properties"
      - "$APP_SCRIPT_PATH/config.toml:/data/config.toml"
      - "$GATEKEEPER_DATAPATH/htpasswd:/htpasswd/htpasswd"
    networks:
      - cyphernodeappsnet
    restart: always
    labels:
      - "traefik.docker.network=cyphernodeappsnet"
      - "traefik.frontend.rule=PathPrefixStrip:/phibox"
      - "traefik.frontend.passHostHeader=true"
      - "traefik.enable=true"
      - "traefik.port=4001"
      - "traefik.frontend.auth.basic.usersFile=/htpasswd/htpasswd"
networks:
  cyphernodeappsnet:
    external: true
